name: Deploy

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: [backend-ci, frontend-ci]

    steps:
      - uses: actions/checkout@v3

      # Backend deployment (example for AWS Elastic Beanstalk)
      - name: Deploy Backend to AWS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: flag-explorer
          environment_name: flag-explorer-prod
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: backend/target/*.jar

      # Frontend deployment (example for Vercel)
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Frontend to Vercel
        working-directory: ./frontend
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}